# Generated by Django 5.0.3 on 2024-03-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_rename_tickets_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.CharField(max_length=20),
        ),
    ]
